// <auto-generated />
namespace CafeDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BooleanIsLimitPropertyAddedInProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BooleanIsLimitPropertyAddedInProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201907051500145_BooleanIsLimitPropertyAddedInProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
